version: '3.9'

services:
  hubs_bot:
    image: markis/hubs-bot:latest
    container_name: hubs_bot
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/arm/v7"
    volumes:
      - ./:/src

