[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hubs_bot"
version = "1.0.0"
authors = ["Markis Taylor <m@rkis.net>"]
description = "hub times bot for r/HudsonOH"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
beautifulsoup4 = "^4.11.2"
praw = "^7.7.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
mypy = "^1.0.1"
ruff = "^0.0.254"
types-requests = "^2.28.11.15"

[tool.poetry.group.test.dependencies]
coverage = {extras = ["toml"], version = "^7.2.1"}
pytest = "^7.2.2"

[tool.coverage.run]
source = ["hubs_bot/"]
omit = ["*/__main__.py"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.black]
target-version = ["py310"]
line-length = 100

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff]
target-version = "py310"
line-length = 100
select = [ "E", "F", "W", "Q", "UP", "I", "N" ]
