[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools >= 40.6.0", 
]

[project]
name = "hubs_bot"
version = "1.0.0"
authors = [
  {name = "Markis Taylor", email = "m@rkis.net"},
]
description = "hub times bot for r/HudsonOH"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "beautifulsoup4~=4.10.0",
  "praw~=7.5.0",
  "requests~=2.26.0",
  "schedule~=1.1.0",
]

[project.optional-dependencies]
dev = [
  "black",
  "build",
  "coverage[toml]",
  "mypy",
  "pytest",
  "types-requests",
  "ruff"
]

[tool.coverage.run]
source = ["hubs_bot/"]
command_line = "venv/bin/pytest"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.black]
target-version = ['py310']
line-length = 100
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
  | venv
)/
'''

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_untyped_decorators = true

[tool.ruff]
target-version = 'py37'
select = [
  "E",
  "F",
  "W",
  "Q",
  "UP",
  "I",
  "N",
]
