name: check

on:
  pull_request:

jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: "pip"
      - run: pip install '.[dev]'
      - run: black --check .

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: "pip"
      - run: pip install '.[dev,test]'
      - run: mypy .

  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: "pip"
      - run: pip install '.[dev]'
      - run: ruff check .

  tests:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: "pip"
      - run: pip install '.[dev,test]'
      - run: pytest --block-network
