name: python check

on:
  pull_request:


jobs:
  black-check:
    name: black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          cache: 'poetry'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run black --check .

  mypy-check:
    name: mypy check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          cache: 'poetry'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run mypy .

  ruff-check:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          cache: 'poetry'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run ruff check .

  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          cache: 'poetry'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest --block-network
